name: Build and Publish Docker

on:
  push:
    branches: ["master"]
    paths-ignore: ["README.md"]
  pull_request:
    branches: ["master"]
    paths-ignore: ["README.md"]

env:
  IMAGE_NAME: ${{ github.repository }}

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image:
          - platform: linux/amd64
            dockerfile: Dockerfile
            tag-main: latest
            tag-alt: ${{ github.sha }}
          - platform: linux/arm64
            dockerfile: Dockerfile.arm64
            tag-main: latest-arm64
            tag-alt: ${{ github.sha }}-arm64
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v2
        with:
          platforms: arm64

      - name: Setup Docker buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ghcr.io/${{ env.IMAGE_NAME }}
          

      - name: Build and push all platforms Docker image
        id: build-and-push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: ${{ matrix.image.platform }}
          file: ${{ matrix.image.dockerfile }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: |
            ghcr.io/${{ env.IMAGE_NAME }}:${{ matrix.image.tag-main }}
            ghcr.io/${{ env.IMAGE_NAME }}:${{ matrix.image.tag-alt }}
            
